version: '3.0'

services:
  web:
    build: ./web
    environment: 
      - APACHE_RUN_USER=#1000
    volumes:
      - ${APP_PATCH_HOST}:${APP_PATCH_CONTAINER}
    ports:
      - 8080:80
    working_dir: ${APP_PATCH_CONTAINER}
    
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${DB_PATCH_HOST}:/var/lib/mysql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080
      
  composer:
      image: composer:2.0
      volumes:
        - ${APP_PATCH_HOST}:${APP_PATCH_CONTAINER}
      working_dir: ${APP_PATCH_CONTAINER}
      command: composer install
      